- README.md
> Update README to use public PyPi repo

- src/braket/_schemas/_version.py
The only way to update a description in PyPi is to upload new files;
however, uploading an existing version is prohibited. The recommended
way to deal with this is with
[post-releases](https://www.python.org/dev/peps/pep-0440/#post-releases).
> fix: Post-release 1.0.0.post1

- README.md
> documentation: Add link to Read the Docs

- src/braket/device_schema/dwave/dwave_provider_level_parameters_v1.py
- test/unit_tests/braket/device_schema/dwave/test_dwave_provider_level_parameters_v1.py
Update the type of some dwave params from int to float. 
Yes, Updated the tests. 
- [ x] I have read the [CONTRIBUTING](https://github.com/aws/amazon-braket-schemas-python/blob/main/CONTRIBUTING.md) doc
- [ x] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/amazon-braket-schemas-python/blob/main/CONTRIBUTING.md#commit-your-change)
- [ x] I have updated any necessary documentation, including [READMEs](https://github.com/aws/amazon-braket-schemas-python/blob/ …
> [Fix] Updating dwave params to float from int. 

- src/braket/_schemas/_version.py
- src/braket/task_result/rigetti_metadata_v1.py
*Description of changes:* Updating the Rigetti program duration to be >= 0 (previously strictly > 0).
*Testing done:* Ran tox to verify that all tests are still passing
> fix: update programDuration to >=0

- src/braket/device_schema/device_action_properties.py
- src/braket/device_schema/device_capabilities.py
- src/braket/device_schema/device_service_properties_v1.py
- src/braket/device_schema/gate_model_parameters_v1.py
- src/braket/device_schema/gate_model_qpu_paradigm_properties_v1.py
- src/braket/device_schema/jaqcd_device_action_properties.py
- src/braket/device_schema/rigetti/rigetti_device_capabilities_v1.py
- src/braket/device_schema/rigetti/rigetti_device_parameters_v1.py
- src/braket/device_schema/rigetti/rigetti_provider_properties_v1.py
> documentation: Correct various typos

- src/braket/_schemas/_version.py
Push the changes to PyPi automatically needs the version to be updated. 
- [ x] I have read the [CONTRIBUTING](https://github.com/aws/amazon-braket-schemas-python/blob/main/CONTRIBUTING.md) doc
- [x ] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/amazon-braket-schemas-python/blob/main/CONTRIBUTING.md#commit-your-change)
- [x ] I have updated any necessary documentation, including …
> change: Bumping version to pull the latest schema changes to PyPi.

- CHANGELOG.md
- CODEOWNERS
- src/braket/_schemas/_version.py
- src/braket/device_schema/gate_model_parameters_v1.py
- src/braket/device_schema/jaqcd_device_action_properties.py
- src/braket/ir/jaqcd/program_v1.py
- test/unit_tests/braket/device_schema/test_gate_model_parameters_v1.py
- test/unit_tests/braket/device_schema/test_jaqcd_device_action_properties.py
- test/unit_tests/braket/task_result/test_task_metadata_v1.py
This is needed to allow customers to run with circuits verbatim
without any automatic rewiring by the QPU, if it is supported.
> feature: Add explicit qubit allocation

- README.md
- tox.ini
> infra: Make tox commands consistent with other repos

- .github/workflows/python-package.yml
- tox.ini
> infra: Upload coverage report to Codecov

- README.md
> infra: Add Codecov badge

- .github/workflows/python-package.yml
- CODEOWNERS
- tox.ini
> infra: Make python-package consistent with other repos

- .github/workflows/dependent-tests.yml
> infra: Run unit tests for dependent packages

- src/braket/device_schema/dwave/__init__.py
- src/braket/device_schema/dwave/dwave_device_level_parameters_v1.py
- src/braket/device_schema/dwave/dwave_device_parameters_v1.py
- src/braket/schema_common/schema_base.py
- src/braket/task_result/task_metadata_v1.py
> add device level parameters and device-specific parameters

- src/braket/schema_common/schema_base.py
> fix: error message typo

- setup.py
- src/braket/device_schema/dwave/dwave_2000Q_device_level_parameters_v1.py
- src/braket/device_schema/dwave/dwave_advantage_device_level_parameters_v1.py
- src/braket/device_schema/dwave/dwave_provider_level_parameters_v1.py
- test/unit_tests/braket/device_schema/dwave/test_dwave_2000Q_device_level_parameters_v1.py
- test/unit_tests/braket/device_schema/dwave/test_dwave_advantage_device_level_parameters_v1.py
- test/unit_tests/braket/device_schema/dwave/test_dwave_device_parameters_v1.py
- test/unit_tests/braket/device_schema/dwave/test_dwave_provider_level_parameters_v1.py
Allow for optional parameters to be explicitly passed in null values
(Note: the fields with Class types are already not validated for type during validation, so those don't need to be modified)
Added unit tests
> allow null values to be passed in for optional parameters

- src/braket/device_schema/dwave/dwave_2000Q_device_parameters_v1.py
- src/braket/device_schema/dwave/dwave_advantage_device_parameters_v1.py
> fix: change documentation for deviceLevelParameters

- src/braket/device_schema/dwave/dwave_2000Q_device_parameters_v1.py
- src/braket/device_schema/dwave/dwave_advantage_device_parameters_v1.py
Reverts aws/amazon-braket-schemas-python#86 (blocked day)
> Revert "fix: change documentation for deviceLevelParameters"

- .github/workflows/python-package.yml
- tox.ini
> infra: tox for GitHub checks

- README.md
> Fix jaqcd typo in README.md

- src/braket/ir/jaqcd/__init__.py
- src/braket/ir/jaqcd/instructions.py
- test/unit_tests/braket/ir/jaqcd/test_quantum_instructions.py
- tox.ini
Adding this gate makes things like CHSH circuits much more manageable off the bat.
*Issue #, if available:* - https://github.com/aws/amazon-braket-sdk-python/pull/297
This edit to the schemas repo based on changes proposed in PR #297 on the sdk repo https://github.com/aws/amazon-braket-sdk-python/pull/297
Added unit test. More information available at: https://github.com/aws/amazon-braket-sdk-python/pull/297
By submitting this pull request, I confirm that my contribution is made under the …
> feature: add control-sqrt-not gate

- src/braket/ir/jaqcd/instructions.py
Fixing the target for MultiQubitPauliChannel from DoubleTarget to MultiTarget. 
tox -e unit-tests
> fix: multiqubit pauli channel with multitarget

- CHANGELOG.md
- README.md
- src/braket/_schemas/_version.py
- src/braket/device_schema/__init__.py
- src/braket/device_schema/device_action_properties.py
- src/braket/device_schema/dwave/dwave_2000Q_device_level_parameters_v1.py
- src/braket/device_schema/ionq/ionq_device_capabilities_v1.py
- src/braket/device_schema/jaqcd_device_action_properties.py
- src/braket/device_schema/openqasm_device_action_properties.py
- src/braket/device_schema/oqc/oqc_device_capabilities_v1.py
- src/braket/device_schema/oqc/oqc_device_parameters_v1.py
- src/braket/device_schema/result_type.py
- src/braket/device_schema/rigetti/rigetti_device_capabilities_v1.py
- src/braket/device_schema/simulators/gate_model_simulator_device_capabilities_v1.py
- src/braket/ir/openqasm/__init__.py
- src/braket/ir/openqasm/program_v1.py
- src/braket/jobs_data/persisted_job_data_v1.py
- src/braket/task_result/additional_metadata.py
- test/unit_tests/braket/device_schema/ionq/test_ionq_device_capabilities_v1.py
- test/unit_tests/braket/device_schema/oqc/test_oqc_device_capabilities_v1.py
- test/unit_tests/braket/device_schema/oqc/test_oqc_device_parameters_v1.py
- test/unit_tests/braket/device_schema/rigetti/test_rigetti_device_capabilities_v1.py
- test/unit_tests/braket/device_schema/simulator/test_gate_model_simulator_device_capabilities_v1.py
- test/unit_tests/braket/device_schema/test_openqasm_device_action_properties.py
- test/unit_tests/braket/device_schema/test_result_type.py
- test/unit_tests/braket/ir/openqasm/test_openqasm_program_v1.py
- test/unit_tests/braket/schema_common/test_schema_base.py
- test/unit_tests/braket/task_result/conftest.py
- test/unit_tests/braket/task_result/test_additional_metadata.py
feature: Add support for running OpenQASM programs
Team tested.
- [ x ] I have read the [CONTRIBUTING](https://github.com/aws/amazon-braket-schemas-python/blob/main/CONTRIBUTING.md) doc
- [ x ] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/amazon-braket-schemas-python/blob/main/CONTRIBUTING.md#commit-your-change)
- [ x ] I have updated any necessary documentation, including …
> feature: Add support for running OpenQASM programs

- src/braket/ir/openqasm/program_v1.py
- src/braket/task_result/oq3_program_result_v1.py
Add schemas for the openqasm native simulator for input/output support. Openqasm program schemas extended to take inputs and a new result type added to support output. `OQ3ProgramResult` is an analog of [`GateModelTaskResult`](https://github.com/aws/amazon-braket-schemas-python/blob/main/src/braket/task_result/gate_model_task_result_v1.py#L38).
e2e tests in other repos covering these schema changes
By submitting this pull request, I confirm that my contribution is …
> Openqasm local simulator

- CHANGELOG.md
- src/braket/_schemas/_version.py
- src/braket/device_schema/__init__.py
- src/braket/device_schema/blackbird_device_action_properties.py
- src/braket/device_schema/continuous_variable_qpu_paradigm_properties_v1.py
- src/braket/device_schema/device_action_properties.py
- src/braket/device_schema/xanadu/__init__.py
- src/braket/device_schema/xanadu/xanadu_device_capabilities_v1.py
- src/braket/device_schema/xanadu/xanadu_device_parameters_v1.py
- src/braket/device_schema/xanadu/xanadu_provider_properties_v1.py
- src/braket/ir/blackbird/__init__.py
- src/braket/ir/blackbird/program_v1.py
- src/braket/task_result/__init__.py
- src/braket/task_result/additional_metadata.py
- src/braket/task_result/gate_model_task_result_v1.py
- src/braket/task_result/photonic_model_task_result_v1.py
- src/braket/task_result/task_metadata_v1.py
- src/braket/task_result/xanadu_metadata_v1.py
- test/unit_tests/braket/device_schema/test_blackbird_device_action_properties.py
- test/unit_tests/braket/device_schema/xanadu/test_xanadu_device_capabilities_v1.py
- test/unit_tests/braket/device_schema/xanadu/test_xanadu_device_parameters_v1.py
- test/unit_tests/braket/device_schema/xanadu/test_xanadu_provider_properties_v1.py
- test/unit_tests/braket/ir/blackbird/test_blackbird_program_v1.py
- test/unit_tests/braket/task_result/conftest.py
- test/unit_tests/braket/task_result/test_additional_metadata.py
- test/unit_tests/braket/task_result/test_gate_model_task_result_v1.py
- test/unit_tests/braket/task_result/test_photonic_model_task_result_v1.py
- test/unit_tests/braket/task_result/test_task_metadata_v1.py
> Sync feature branch with main

- .github/workflows/dependent-tests.yml
- .gitignore
> infra: Add SF plugin to dependent tests

- .github/workflows/dependent-tests.yml
- .github/workflows/python-package.yml
> infra: Add feature branch pull request tests

- src/braket/ir/ahs/__init__.py
- src/braket/ir/ahs/atom_arrangement.py
- src/braket/ir/ahs/physical_field.py
- src/braket/ir/ahs/program_v1.py
- src/braket/ir/ahs/time_series.py
- test/unit_tests/braket/ir/ahs/test_ahs_program_v1.py
- test/unit_tests/braket/ir/ahs/test_atom_arrangement.py
- test/unit_tests/braket/ir/ahs/test_driving_field.py
- test/unit_tests/braket/ir/ahs/test_physical_field.py
- test/unit_tests/braket/ir/ahs/test_shifting_field.py
- test/unit_tests/braket/ir/ahs/test_time_series.py
Harmonizing names of AHS IR to resemble more closely the names used in the AHS module of the Braket SDK.
Yes, see tests in `test/unit_tests/braket/ir/ahs/`
> Quera harmonize names

- src/braket/device_schema/oqc/oqc_device_capabilities_v1.py
- src/braket/device_schema/pulse/frame_v1.py
- src/braket/device_schema/pulse/port_v1.py
- src/braket/device_schema/pulse/pulse_device_action_properties_v1.py
- src/braket/device_schema/pulse/pulse_function_v1.py
- src/braket/device_schema/rigetti/rigetti_device_capabilities_v1.py
- test/unit_tests/braket/device_schema/pulse/test_pulse_device_action_properties_v1.py
> feature: Add support for pulses

- src/braket/device_schema/quera/quera_ahs_paradigm_properties_v1.py
- src/braket/ir/ahs/program_v1.py
- test/unit_tests/braket/device_schema/quera/test_quera_ahs_paradigm_properties_v1.py
- test/unit_tests/braket/ir/ahs/test_ahs_program_v1.py
This is a collection of small changes, mainly to clean up the code and to comply with the results returned by the GetDevice API endpoint.
* Docstring changes
* Removed unused modules
* Removed 1- and 2-qubit fidelity metric (and associated tests)
No new tests. Existing tests are passing.
> breaking: Quera polish

- README.md
*Description of changes:* This pr updates readme to remove superseded ir types from examples.
*Testing done:* Run updated code in remaining examples.
> documentation: remove ir types from examples

- .github/workflows/dependent-tests.yml
- .github/workflows/python-package.yml
- src/braket/task_result/gate_model_task_result_v1.py
> update: adding build for python 3.10

- .github/workflows/dependent-tests.yml
- .github/workflows/publish-to-pypi.yml
- .github/workflows/python-package.yml
- README.md
https://github.com/badges/shields/issues/8671
https://github.com/aws-samples/amazon-braket-algorithm-library/commit/40bf548380c56ce4fa95f88e5071ca532a677701
> infra: update github workflows for node12 retirement

- README.md
Removing for consistency with other repositories, where the change was made because the badge offers no useful information.
> doc: Remove Black badge

- src/braket/device_schema/openqasm_device_action_properties.py
- src/braket/ir/openqasm/modifiers.py
- test/unit_tests/braket/device_schema/test_openqasm_device_action_properties.py
Add schema for supported gate modifiers
Unit test added to ensure no regression
> feat: supportedModifiers schema

- src/braket/ir/openqasm/modifiers.py
Require specific modifier name for name field
manual and unit
> fix: constrain modifier name string

- src/braket/device_schema/error_mitigation/__init__.py
- src/braket/device_schema/error_mitigation/debias.py
- src/braket/device_schema/error_mitigation/error_mitigation_properties.py
- src/braket/device_schema/error_mitigation/error_mitigation_scheme.py
- src/braket/device_schema/ionq/ionq_device_capabilities_v1.py
- src/braket/device_schema/ionq/ionq_device_parameters_v1.py
- src/braket/device_schema/ionq/ionq_provider_properties_v1.py
- src/braket/ir/openqasm/program_v1.py
- src/braket/schema_common/schema_header.py
- src/braket/task_result/__init__.py
- src/braket/task_result/additional_metadata.py
- src/braket/task_result/ionq_metadata_v1.py
- test/unit_tests/braket/device_schema/ionq/test_ionq_device_capabilities_v1.py
- test/unit_tests/braket/device_schema/ionq/test_ionq_device_parameters_v1.py
- test/unit_tests/braket/device_schema/ionq/test_ionq_provider_properties_v1.py
- test/unit_tests/braket/task_result/conftest.py
- test/unit_tests/braket/task_result/test_additional_metadata.py
- test/unit_tests/braket/task_result/test_ionq_metadata_v1.py
> feat: Introduce error mitigation

- setup.cfg
- setup.py
- tox.ini
> infra: add a linter to check proper rst formatting and fix up incorrect docs

- .github/workflows/dependent-tests.yml
- .github/workflows/twine-check.yml
> infra: Don't run dependent tests and twine check on push

- .github/workflows/python-package.yml
- setup.py
feat: add support for python 3.11
> feat: add support for python 3.11

- src/braket/device_schema/pulse/pulse_device_action_properties_v1.py
adding native gate calibrations href to pulse properties
- [X ] I have read the [CONTRIBUTING](https://github.com/aws/amazon-braket-schemas-python/blob/main/CONTRIBUTING.md) doc
- [X ] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/amazon-braket-schemas-python/blob/main/CONTRIBUTING.md#commit-your-change)
- [ X] I have updated any necessary documentation, including [READMEs](https://github.com/aws/amazon-braket-schemas-python/blob/ …
> feat: adding native gate calibrations href to pulse properties

- .github/workflows/dependent-tests.yml
> infra: Remove SF plugin, add Python 3.11 to dependent tests

- README.md
- src/braket/device_schema/pulse/native_gate_calibrations_v1.py
- src/braket/device_schema/pulse/pulse_device_action_properties_v1.py
> feat: add the native gate calibration schema

- src/braket/device_schema/pulse/native_gate_calibrations_v1.py
- [ x] I have read the [CONTRIBUTING](https://github.com/aws/amazon-braket-schemas-python/blob/main/CONTRIBUTING.md) doc
- [ x] I have updated any necessary documentation, including [READMEs](https://github.com/aws/amazon-braket-schemas-python/blob/main/README.md) and [API docs](https://github.com/aws/amazon-braket-schemas-python/blob/main/CONTRIBUTING.md#documentation-guidelines) (if appropriate)
- [x ] I have added tests that prove my fix is effective or that my …
> fix: Specify waveform types

- .readthedocs.yml
https://blog.readthedocs.com/use-build-os-config/
tox
> infra: readthedocs integration change

- .github/pull_request_template.md
- CONTRIBUTING.md
- README.md
- doc/index.rst
- setup.py
> doc: Replace aws org with amazon-braket

- .github/workflows/code-freeze.yml
- .github/workflows/twine-check.yml
add code freeze workflow
tested in sdk, workflow will run for this branch
> infra: code freeze

- .github/workflows/code-freeze.yml
support lack of frozen prefix
validated in other repos
> infra: code freeze update

- .github/workflows/publish-to-pypi.yml
> fix: add setuptools to the publish workflow

- src/braket/device_schema/quera/quera_ahs_paradigm_properties_v1.py
Update doc string for atomLossProbabilityWorst
> fix: update quera_ahs_paradigm doc string

- .github/workflows/dependent-tests.yml
> fix: restore dependent tests after the Pydantic migration

- src/braket/ir/ahs/__init__.py
> fix: add local detuning export

- src/braket/device_schema/iqm/__init__.py
- src/braket/device_schema/iqm/iqm_device_capabilities_v1.py
- src/braket/device_schema/iqm/iqm_device_parameters_v1.py
- src/braket/device_schema/iqm/iqm_provider_properties_v1.py
- src/braket/task_result/additional_metadata.py
- src/braket/task_result/iqm_metadata_v1.py
- src/braket/task_result/task_metadata_v1.py
- test/unit_tests/braket/device_schema/iqm/test_iqm_device_capabilities_v1.py
- test/unit_tests/braket/device_schema/iqm/test_iqm_device_parameters_v1.py
- test/unit_tests/braket/device_schema/iqm/test_iqm_provider_properties_v1.py
- test/unit_tests/braket/task_result/conftest.py
- test/unit_tests/braket/task_result/test_additional_metadata.py
- test/unit_tests/braket/task_result/test_task_metadata_v1.py
> feat: add iqm schemas

- test/unit_tests/braket/device_schema/xanadu/test_xanadu_device_parameters_v1.py
fix: update xanadu tests to use with pytest.raise
> fix: update xanadu tests to use with pytest.raise

- .github/dependabot.yml
This will keep our GH actions up to date.
> infra: add dependabot for github actions

- src/braket/device_schema/quera/quera_ahs_paradigm_properties_v1.py
- src/braket/device_schema/rigetti/__init__.py
- src/braket/device_schema/rigetti/rigetti_device_capabilities_v2.py
- src/braket/device_schema/rigetti/rigetti_provider_properties_v2.py
- test/unit_tests/braket/device_schema/rigetti/test_rigetti_device_capabilities_v2.py
- test/unit_tests/braket/device_schema/rigetti/test_rigetti_provider_properties_v2.py
This adds a Rigetti props v2 schema
`tox`
> feat: add rigetti device properties v2 schemas

- src/braket/device_schema/device_connectivity.py
Fixes the schema for connectivity
> fix: constrain device connectivitiy

- src/braket/device_schema/__init__.py
- src/braket/device_schema/standardized_gate_model_qpu_device_properties_v2.py
- test/unit_tests/braket/device_schema/test_standardized_gate_model_qpu_device_properties_v2.py
> feat: add standardized v2

- src/braket/device_schema/__init__.py
- src/braket/device_schema/standardized_gate_model_qpu_device_properties_v3.py
- test/unit_tests/braket/device_schema/test_standardized_gate_model_qpu_device_properties_v3.py
adding new version of standardized gate model QPU device properties v3
> change: Add standardized gate model QPU device properties v3

- src/braket/device_schema/ionq/ionq_device_capabilities_v1.py
- test/unit_tests/braket/device_schema/ionq/test_ionq_device_capabilities_v1.py
code: updating IonQ device capability schema to include standardized property
> fix: updating IonQ device capability schema to include standardized property

- src/braket/device_schema/device_action_properties.py
- src/braket/device_schema/iqm/iqm_device_capabilities_v1.py
- src/braket/device_schema/openqasm_program_set_device_action_properties.py
- src/braket/device_schema/rigetti/rigetti_device_capabilities_v1.py
- src/braket/device_schema/rigetti/rigetti_device_capabilities_v2.py
- src/braket/ir/openqasm/__init__.py
- src/braket/ir/openqasm/program_set_v1.py
- src/braket/task_result/__init__.py
- src/braket/task_result/additional_metadata.py
- src/braket/task_result/program_result_v1.py
- src/braket/task_result/program_set_executable_cancellation_v1.py
- src/braket/task_result/program_set_executable_failure_v1.py
- src/braket/task_result/program_set_executable_result_v1.py
- src/braket/task_result/program_set_task_metadata_v1.py
- src/braket/task_result/program_set_task_result_v1.py
- test/unit_tests/braket/device_schema/iqm/test_iqm_device_capabilities_v1.py
- test/unit_tests/braket/device_schema/rigetti/test_rigetti_device_capabilities_v1.py
- test/unit_tests/braket/device_schema/rigetti/test_rigetti_device_capabilities_v2.py
- test/unit_tests/braket/device_schema/test_openqasm_program_set_device_action_properties.py
- test/unit_tests/braket/ir/openqasm/test_openqasm_program_set_v1.py
- test/unit_tests/braket/ir/openqasm/test_programs.py
- test/unit_tests/braket/task_result/conftest.py
- test/unit_tests/braket/task_result/test_additional_metadata.py
- test/unit_tests/braket/task_result/test_gate_model_task_result_v1.py
- test/unit_tests/braket/task_result/test_program_set_task_result_v1.py
> feat: Program sets
